BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: '30'
            font_size: 30
            multiline: False
            size_hint: 2, 1
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.increment_value(int(input_number.text), 1)
            Button:
                text: 'Down'
                on_press: app.increment_value(int(input_number.text), -1)
    Button:
        text: 'Convert miles to km'
        on_press: app.convert_miles_to_km(int(input_number.text))
    Label:
        id: output_label
        font_size: 40
        color: (1, 0.9, 0, 1)